package cit360teamproject.HibernateFiles;

 
// Generated Mar 8, 2016 11:54:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Scoutinfo generated by hbm2java
 */
public class Scoutinfo  implements java.io.Serializable {


     private String scoutfirstname;
     private String scoutlastname;
     private Date scoutdob;

    public Scoutinfo() {
    }

	
    public Scoutinfo(String scoutfirstname) {
        this.scoutfirstname = scoutfirstname;
    }
    public Scoutinfo(String scoutfirstname, String scoutlastname, Date scoutdob) {
       this.scoutfirstname = scoutfirstname;
       this.scoutlastname = scoutlastname;
       this.scoutdob = scoutdob;
    }
   
    public String getScoutfirstname() {
        return this.scoutfirstname;
    }
    
    public void setScoutfirstname(String scoutfirstname) {
        this.scoutfirstname = scoutfirstname;
    }
    public String getScoutlastname() {
        return this.scoutlastname;
    }
    
    public void setScoutlastname(String scoutlastname) {
        this.scoutlastname = scoutlastname;
    }
    public Date getScoutdob() {
        return this.scoutdob;
    }
    
    public void setScoutdob(Date scoutdob) {
        this.scoutdob = scoutdob;
    }




}


